[versions]
agp = "8.13.2"
kotlin = "2.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
composeBom = "2025.12.01"
material = "1.13.0"
dokka = "2.1.0"
sonarqube = "7.2.2.6593"
mockk = "1.14.7"
testCoreKtx = "1.7.0"
publish = "0.35.0"
robolectric = "4.16"
kotlinReflect = "2.2.0"
iruruetaGeometry = "1.4.0"
iruruetaTestUtils = "1.3.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "testCoreKtx" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlinReflect" }
irurueta-geometry = { group = "com.irurueta", name = "irurueta-geometry", version.ref = "iruruetaGeometry" }
irurueta-test-utils = { group = "com.irurueta", name = "irurueta-android-test-utils", version.ref= "iruruetaTestUtils" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
